services:
  - type: web
    name: card-processor-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8480622059:AAHKRrUQK6Gw0ACZLiBLYwc9Cf9laodogVM
      - key: AUTHOR
        value: "@FAHIM0200"
    autoDeploy: true
